### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by skywodd** [TamiaLab/PySkCode#7]
Todo list
- [x] Unittest of the titles utility
- [x] Unittest of the smileys utility
- [x] Unittest of the cosmetics utility
- [x] Unittest of the paragraphs utility
- [x] Unittest of the builder core module
- [x] Unittest of the render core module
- [x] Unittest of the treebuilder core module
- [x] Unittest of the tools core module
- [x] Unittest of the etree core module
- [x] Unittest of the tokenizer core module
